version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    env_file: 
      - ./.env.sample
  app:
    build: ./
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    env_file: 
      - ./.env.sample
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
